- name: Add, manage users and groups on a remote host from the list
  hosts: all_workers
  become: true

  vars_files:
    - ~/05.Ansible/vars/list_user.yml
    #Retrieves variables from the list

  tasks:
    - name: Create groups
      group:
        name: "{{ item.name }}"
        state: present
      loop: "{{ addgroup }}"

    - name: Create users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        password: "{{ item.password | password_hash('sha512') }}"
        #Password Hashing
        state: present
      loop: "{{ addusers }}"
